<a href="https://colab.research.google.com/github/VOL-EM2024/mo/blob/main/%D0%97%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Задание по практике 3

##Обработка пропущенных значений

Обработайте пропущенные значения:


* Удалите пропущенные значения
* Заполните при помощи медианы, среднего для числовых значений
* Заполните при помощи моды для категориальных значений
* Интерполируйте
Выведите статистку после каждого метода и объясните

In [49]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (1.2.2)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.23.5)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.11.3)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (3.2.0)

In [50]:
import pandas as pd

df = pd.read_csv('/content/global-data-on-sustainable-energy (1).csv')
df

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
0,Afghanistan,2000.0,1.613591,6.2,9.22,20000.0,44.99,0.16,0.0,0.31,...,302.59482,1.64,760.000000,NaN,NaN,NaN,60.0,652230.0,33.939110,67.709953
1,Afghanistan,2001.0,4.074574,7.2,8.86,130000.0,45.60,0.09,0.0,0.50,...,236.89185,1.74,730.000000,NaN,NaN,NaN,60.0,652230.0,33.939110,67.709953
2,Afghanistan,2002.0,9.409158,8.2,8.47,3950000.0,37.83,0.13,0.0,0.56,...,210.86215,1.40,1029.999971,NaN,NaN,179.426579,60.0,652230.0,33.939110,67.709953
3,Afghanistan,2003.0,14.738506,9.5,8.09,25970000.0,36.66,0.31,0.0,0.63,...,229.96822,1.40,1220.000029,NaN,8.832278,190.683814,60.0,652230.0,33.939110,67.709953
4,Afghanistan,2004.0,20.064968,10.9,7.75,NaN,44.24,0.33,0.0,0.56,...,204.23125,1.20,1029.999971,NaN,1.414118,211.382074,60.0,652230.0,33.939110,67.709953
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3644,Zimbabwe,2016.0,42.561730,29.8,62.88,30000.0,81.90,3.50,0.0,3.32,...,3227.68020,10.00,11020.000460,NaN,0.755869,1464.588957,38.0,390757.0,-19.015438,29.154857
3645,Zimbabwe,2017.0,44.178635,29.8,62.33,5570000.0,82.46,3.05,0.0,4.30,...,3068.01150,9.51,10340.000150,NaN,4.709492,1235.189032,38.0,390757.0,-19.015438,29.154857
3646,Zimbabwe,2018.0,45.572647,29.9,82.53,10000.0,80.23,3.73,0.0,5.46,...,3441.98580,9.83,12380.000110,NaN,4.824211,1254.642265,38.0,390757.0,-19.015438,29.154857
3647,Zimbabwe,2019.0,46.781475,30.1,81.40,250000.0,81.50,3.66,0.0,4.58,...,3003.65530,10.47,11760.000230,NaN,-6.144236,1316.740657,38.0,390757.0,-19.015438,29.154857
3648,Zimbabwe,2020.0,52.747670,30.4,80.61,30000.0,81.90,3.40,0.0,4.19,...,2680.13180,10.00,NaN,NaN,-6.248748,1214.509820,38.0,390757.0,-19.015438,29.154857

In [51]:
df_cleaned = df.dropna()
df_cleaned #Удаление

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
43,Algeria,2001.0,98.96687,97.30,8.79,810000.0,0.43,24.96,0.0,0.07,...,9961.640,4.07,78650.00000,0.065218,3.000000,1740.606654,18.0,2381741.0,28.033886,1.659626
44,Algeria,2002.0,98.95306,97.80,8.68,310000.0,0.51,25.94,0.0,0.06,...,10180.350,4.12,82400.00153,0.051677,5.600000,1781.828908,18.0,2381741.0,28.033886,1.659626
45,Algeria,2003.0,98.93401,98.00,8.57,90000.0,0.47,27.54,0.0,0.26,...,10510.461,4.08,88190.00244,0.228104,7.200000,2103.381291,18.0,2381741.0,28.033886,1.659626
46,Algeria,2004.0,98.91208,98.20,8.46,140000.0,0.44,29.14,0.0,0.25,...,10759.022,3.96,89489.99786,0.206787,4.300000,2610.185422,18.0,2381741.0,28.033886,1.659626
47,Algeria,2005.0,98.88961,98.50,8.34,160000.0,0.58,31.36,0.0,0.55,...,11113.723,3.90,94190.00244,0.434119,5.900000,3113.094883,18.0,2381741.0,28.033886,1.659626
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3559,Uzbekistan,2015.0,100.00000,85.35,60.83,270000.0,1.71,47.55,0.0,7.00,...,17386.195,7.86,99169.99817,3.012993,7.218774,2753.971072,79.0,447400.0,41.377491,64.585262
3560,Uzbekistan,2016.0,100.00000,85.20,59.88,690000.0,1.61,48.75,0.0,7.25,...,16374.342,7.82,105230.00340,3.567936,5.932151,2704.677188,79.0,447400.0,41.377491,64.585262
3561,Uzbekistan,2017.0,100.00000,84.90,58.24,60130000.0,1.75,49.71,0.0,8.35,...,16642.676,7.88,109529.99880,3.972285,4.395275,1916.764642,79.0,447400.0,41.377491,64.585262
3562,Uzbekistan,2018.0,100.00000,84.30,59.09,84130000.0,1.49,53.58,0.0,5.85,...,16445.740,9.05,112470.00120,2.927033,5.354997,1597.068337,79.0,447400.0,41.377491,64.585262
3563,Uzbekistan,2019.0,100.00000,84.60,57.96,65940000.0,1.57,53.64,0.0,6.47,...,16212.221,8.37,116709.99910,3.197033,5.709632,1784.009816,79.0,447400.0,41.377491,64.585262

Мы удалили все строки, которые содержали  NaN. Если посмотреть на первую таблицу, можем увидить, что изначально строк было 3649, а после наших действий стало 324.Следовательно мы удалили строки).

In [52]:
df_cleaned.gdp_growth.describe()

count    324.000000
mean       4.492573
std        4.413222
min      -36.658153
25%        2.597033
50%        4.391612
75%        6.504695
max       34.500000
Name: gdp_growth, dtype: float64

In [53]:
df_median = df.fillna(df.median())
df_median #Заполнение при помощи медианы

<ipython-input-53-fb903157e4ef>:1: FutureWarning: The default value of numeric_only in DataFrame.median is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df_median = df.fillna(df.median())

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
0,Afghanistan,2000.0,1.613591,6.2,9.22,20000.0,44.99,0.16,0.0,0.31,...,302.59482,1.64,760.000000,6.650065,3.506345,4442.009319,60.0,652230.0,33.939110,67.709953
1,Afghanistan,2001.0,4.074574,7.2,8.86,130000.0,45.60,0.09,0.0,0.50,...,236.89185,1.74,730.000000,6.650065,3.506345,4442.009319,60.0,652230.0,33.939110,67.709953
2,Afghanistan,2002.0,9.409158,8.2,8.47,3950000.0,37.83,0.13,0.0,0.56,...,210.86215,1.40,1029.999971,6.650065,3.506345,179.426579,60.0,652230.0,33.939110,67.709953
3,Afghanistan,2003.0,14.738506,9.5,8.09,25970000.0,36.66,0.31,0.0,0.63,...,229.96822,1.40,1220.000029,6.650065,8.832278,190.683814,60.0,652230.0,33.939110,67.709953
4,Afghanistan,2004.0,20.064968,10.9,7.75,5570000.0,44.24,0.33,0.0,0.56,...,204.23125,1.20,1029.999971,6.650065,1.414118,211.382074,60.0,652230.0,33.939110,67.709953
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3644,Zimbabwe,2016.0,42.561730,29.8,62.88,30000.0,81.90,3.50,0.0,3.32,...,3227.68020,10.00,11020.000460,6.650065,0.755869,1464.588957,38.0,390757.0,-19.015438,29.154857
3645,Zimbabwe,2017.0,44.178635,29.8,62.33,5570000.0,82.46,3.05,0.0,4.30,...,3068.01150,9.51,10340.000150,6.650065,4.709492,1235.189032,38.0,390757.0,-19.015438,29.154857
3646,Zimbabwe,2018.0,45.572647,29.9,82.53,10000.0,80.23,3.73,0.0,5.46,...,3441.98580,9.83,12380.000110,6.650065,4.824211,1254.642265,38.0,390757.0,-19.015438,29.154857
3647,Zimbabwe,2019.0,46.781475,30.1,81.40,250000.0,81.50,3.66,0.0,4.58,...,3003.65530,10.47,11760.000230,6.650065,-6.144236,1316.740657,38.0,390757.0,-19.015438,29.154857
3648,Zimbabwe,2020.0,52.747670,30.4,80.61,30000.0,81.90,3.40,0.0,4.19,...,2680.13180,10.00,10239.999770,6.650065,-6.248748,1214.509820,38.0,390757.0,-19.015438,29.154857

Мы заменили значение NaN при помощи медианы.

In [ ]:
df_median.gdp_growth.describe()

In [ ]:
df_mean = df.fillna(df.mean())
df_mean #Заполнение при помощи среднего

Тк нужно заменить NaN, мы используем метод заполнения средним.

In [ ]:
df_mean.gdp_growth.describe()

In [ ]:
df_mode = df.fillna(df["gdp_growth"].mode()[0])
df_mode #Заполнение при помощи моды

Мы заменили значение NaN при помощи моды.

In [ ]:
df_mode.gdp_growth.describe()

In [ ]:
df_interpolated = df.interpolate()
df_interpolated #Заполнение при помощи интерполяции

Используем интерполяцию для заполнения пропущенных значений.(Интерполяция – способ нахождения промежуточных значений, между двумя известными значениями.)

In [ ]:
df_interpolated.gdp_growth.describe()

Вывод: исходя из статистики, мы можем сделать вывод о том, что в данной ситуации не важно каким из способов обрабатывать пропущенные значения, так как начальные данные после применения этих методов почти не изменились.

##Поиск выбросов и аномалий

**Те, кто выполняет задания со * делают поиск выбросов с помощью написанного ранее класса**

Найти выбросы по числовой переменной (использовать метод основанный на среднем и на межквартильном размахе). Объясните результат

Вывести статистику с выбросами и без. Сравните и объясните результат

In [ ]:
import matplotlib.pyplot as plt
df = df.dropna()
plt.boxplot(df["gdp_growth"])
plt.show() #Методом среднего

выбросы есть

In [ ]:
df["gdp_growth"].describe()

In [ ]:
mean = df["gdp_growth"].mean()
std_deviation = df["gdp_growth"].std()
threshold = 3 * std_deviation

# Идентифицируем выбросы
outliers = [x for x in df["gdp_growth"] if abs(x - mean) > threshold]

# Выводим результаты
print("Среднее значение данных:", mean)
print("Стандартное отклонение данных:", std_deviation)
print("Потенциальные выбросы:", outliers) #Методом среднего

In [ ]:
Q1 = df["gdp_growth"].quantile(0.25)
Q3 = df["gdp_growth"].quantile(0.75)
IQR = Q3-Q1
lower = Q1 - 1.5*IQR
upper = Q3 + 1.5*IQR

outliers2 = [x1 for x1 in df["gdp_growth"] if ((x1 < lower) or (x1 > upper))]#При помощи межквартильного размаха

print("Потенциальные выбросы:", outliers2)

Вывод: после поиска выбросов двумя разными методами,мы учидели, что и в 1 и во 2 мтоде выбросами являются 27.96153807, 34.5, -36.65815267.

**Объяснения**

##Дубликаты

Проверьте датафрейм на дубликаты и удалите их, если дублей нет - создайте.

In [ ]:
df_duplicated = df[df.duplicated()]
df_duplicated #Проверка на дубли

Дублей нет, поэтому их нужно создать.

In [ ]:
df.loc[len(df)] = df.iloc[1]
df #Создание дублей

In [ ]:
df_duplicated = df[df.duplicated()]
df_duplicated #Ещё раз проверяем

In [ ]:
df_duplicates = df.drop_duplicates()
df_duplicates #Удаление дублей

мы добавили, и мы удалили...

## Преобразование признаков

In [ ]:
# получаем числовые признаки
num_features = df.select_dtypes(include=['float64']).columns

num_features

In [ ]:
df.gdp_growth.unique()

Масштабируйте числовые признаки через MinMaxScaler, StandardScaler

In [ ]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

# MinMax масштабирование
scaler_minmax = MinMaxScaler()
df_minmax_scaled = df.copy()
df_minmax_scaled[num_features] = scaler_minmax.fit_transform(df[num_features])
df_minmax_scaled.gdp_growth.unique() # преобразованные уникальные значения в числовом призанке в диапозоне [0, 1]

In [ ]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
# Standard масштабирование
standard_scaler = StandardScaler()
df_standard_scaler = df.copy()
df_standard_scaler[num_features] = standard_scaler.fit_transform(df[num_features])
df_standard_scaler.gdp_growth.unique()

Масштабируйте категориальные признаки через OneHotEncoder

In [ ]:
df.info()

In [73]:
num_features = df.select_dtypes(include=['category']).columns

num_features

Index([], dtype='object')

In [ ]:
df["Entity"] = df["Entity"].astype("category")

cat_features = df.select_dtypes(include=['category']).columns

from sklearn.preprocessing import OneHotEncoder

# Применяем OneHotEncoder
encoder = OneHotEncoder(sparse=False, drop='first')
encoded_features = encoder.fit_transform(df[cat_features])

# Получаем имена новых признаков
encoded_columns = encoder.get_feature_names_out(cat_features)
encoded_columns

In [81]:
encoded = pd.get_dummies(df, columns=cat_features, drop_first=True)
encoded

,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),Low-carbon electricity (% electricity),...,Entity_Mexico,Entity_Morocco,Entity_Pakistan,Entity_Peru,Entity_Philippines,Entity_South Africa,Entity_Sri Lanka,Entity_Thailand,Entity_Turkmenistan,Entity_Uzbekistan
43,2001.0,98.96687,97.30,8.79,810000.0,0.43,24.96,0.0,0.07,0.279664,...,0,0,0,0,0,0,0,0,0,0
44,2002.0,98.95306,97.80,8.68,310000.0,0.51,25.94,0.0,0.06,0.230769,...,0,0,0,0,0,0,0,0,0,0
45,2003.0,98.93401,98.00,8.57,90000.0,0.47,27.54,0.0,0.26,0.935252,...,0,0,0,0,0,0,0,0,0,0
46,2004.0,98.91208,98.20,8.46,140000.0,0.44,29.14,0.0,0.25,0.850630,...,0,0,0,0,0,0,0,0,0,0
47,2005.0,98.88961,98.50,8.34,160000.0,0.58,31.36,0.0,0.55,1.723598,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3559,2015.0,100.00000,85.35,60.83,270000.0,1.71,47.55,0.0,7.00,12.832264,...,0,0,0,0,0,0,0,0,0,1
3560,2016.0,100.00000,85.20,59.88,690000.0,1.61,48.75,0.0,7.25,12.946428,...,0,0,0,0,0,0,0,0,0,1
3561,2017.0,100.00000,84.90,58.24,60130000.0,1.75,49.71,0.0,8.35,14.381675,...,0,0,0,0,0,0,0,0,0,1
3562,2018.0,100.00000,84.30,59.09,84130000.0,1.49,53.58,0.0,5.85,9.843514,...,0,0,0,0,0,0,0,0,0,1
3563,2019.0,100.00000,84.60,57.96,65940000.0,1.57,53.64,0.0,6.47,10.763600,...,0,0,0,0,0,0,0,0,0,1

Ивините, но это ужас а не датсет. Даже комментировать не хочется

##Задание для гениев*


Реализовать расчет корреляции Спирмана

In [ ]:
#Функция по расчету тут

In [ ]:
#Пример использования тут и объяснение принципа работы

###Пример реализации

In [ ]:
import pandas as pd
import numpy as np


def corr_pearson(column_1, column_2):
  cov = np.cov(column_1, column_2)
  return cov/(column_1.std() * column_2.std())

In [ ]:
data = {
    'Рост': [170, 155, 180, 162, 175],
    'Вес': [65, 50, 75, 55, 70]
}
df = pd.DataFrame(data)
df

   Рост  Вес
0   170   65
1   155   50
2   180   75
3   162   55
4   175   70

In [ ]:
corr_pearson(df["Рост"], df["Вес"])

array([[0.96593129, 0.99674864],
       [0.99674864, 1.03527033]])