<a href="https://colab.research.google.com/github/VOL-EM2024/mo/blob/main/%22%D0%97%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5_1/2_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Задание по практике 1

##Загрузка датасета
В файле classification datasets расположены ссылки на датасеты. Выберите один в соответствии со своим вариантом, скачайте и прочитайте файл
hghg
**Не забудьте загрузить нужные библиотеки**

Например: pip3 install pandas

In [2]:
import pandas as pd

In [12]:
df = pd.read_csv("/content/global-data-on-sustainable-energy (1).csv")
df

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
0,Afghanistan,2000.0,1.613591,6.2,9.22,20000.0,44.99,0.16,0.0,0.31,...,302.59482,1.64,760.000000,NaN,NaN,NaN,60.0,652230.0,33.939110,67.709953
1,Afghanistan,2001.0,4.074574,7.2,8.86,130000.0,45.60,0.09,0.0,0.50,...,236.89185,1.74,730.000000,NaN,NaN,NaN,60.0,652230.0,33.939110,67.709953
2,Afghanistan,2002.0,9.409158,8.2,8.47,3950000.0,37.83,0.13,0.0,0.56,...,210.86215,1.40,1029.999971,NaN,NaN,179.426579,60.0,652230.0,33.939110,67.709953
3,Afghanistan,2003.0,14.738506,9.5,8.09,25970000.0,36.66,0.31,0.0,0.63,...,229.96822,1.40,1220.000029,NaN,8.832278,190.683814,60.0,652230.0,33.939110,67.709953
4,Afghanistan,2004.0,20.064968,10.9,7.75,NaN,44.24,0.33,0.0,0.56,...,204.23125,1.20,1029.999971,NaN,1.414118,211.382074,60.0,652230.0,33.939110,67.709953
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3644,Zimbabwe,2016.0,42.561730,29.8,62.88,30000.0,81.90,3.50,0.0,3.32,...,3227.68020,10.00,11020.000460,NaN,0.755869,1464.588957,38.0,390757.0,-19.015438,29.154857
3645,Zimbabwe,2017.0,44.178635,29.8,62.33,5570000.0,82.46,3.05,0.0,4.30,...,3068.01150,9.51,10340.000150,NaN,4.709492,1235.189032,38.0,390757.0,-19.015438,29.154857
3646,Zimbabwe,2018.0,45.572647,29.9,82.53,10000.0,80.23,3.73,0.0,5.46,...,3441.98580,9.83,12380.000110,NaN,4.824211,1254.642265,38.0,390757.0,-19.015438,29.154857
3647,Zimbabwe,2019.0,46.781475,30.1,81.40,250000.0,81.50,3.66,0.0,4.58,...,3003.65530,10.47,11760.000230,NaN,-6.144236,1316.740657,38.0,390757.0,-19.015438,29.154857
3648,Zimbabwe,2020.0,52.747670,30.4,80.61,30000.0,81.90,3.40,0.0,4.19,...,2680.13180,10.00,NaN,NaN,-6.248748,1214.509820,38.0,390757.0,-19.015438,29.154857

##Первое знакомство с датасетом
В следующих ячейках выведите:


1.   Колонки датасета
2.   Первые 5 значений
3.   Последние 5 значений
4.   Статистику по числовым колонкам

In [ ]:
#Колонки
df.columns

In [ ]:
#Первые 5 значений
df.head(5)

In [ ]:
#Последние 5 значений
df.tail(5)

In [ ]:
#Статистику
df.describe()

**Ответьте на следующие вопросы:**


1.   Какие средние значения в каждой числовой колонке вашего датасета?
2.   Минимальные и максимальные значения в каждой числовой колонке вашего датасета



1.   **Ответ 1. 2010.038367	78.933702	63.255287	113.137498	9.422400e+07	32.638165	70.365003	13.450190	23.968010	36.801182	25743.981745	5.307345	1.598665e+05	11.986707	3.441610	13283.774348	6.332135e+05	18.246388	14.822695**
2.   **Ответ 2. min - 2000.000000	1.252269	0.000000	0.000000	0.000000e+00	0.000000	0.000000	0.000000	0.000000	0.000000	0.000000	0.110000	1.000000e+01	0.000000	-62.075920	111.927225	2.100000e+01	-40.900557	-175.198242
max -  2020.000000	100.000000	100.000000	3060.190000	5.202310e+09	96.040000	5184.130000	809.410000	2184.940000	100.000010	262585.700000	32.570000	1.070722e+07	86.836586	123.139555	123514.196700	9.984670e+06	64.963051	178.065032**

##Типизация
Присвойте соответствующим колонкам один из типов (category, float, int)

In [ ]:
df.columns

In [ ]:
df["Financial flows to developing countries (US $)"].fillna(0).astype("int64")

In [ ]:

df.info()
#Вывести типы колонок тут

Какие признаки вы можете выделить в своем датасете (категориальные, числовые и др., **минимум 3 разных**, помните что можно также выделить признаки более точно, например числовые - порядковые, количественные и т.д.)?

##Фильтрация
Офильтруйте 3 колонки вашего датасета и выведите результат

In [ ]:
fil1_df=df[['Year','Latitude']]
fil1_df

In [ ]:
fil2_df=df[['Latitude','Longitude']]
fil2_df

In [ ]:
fil3_df=df[['Electricity from fossil fuels (TWh)','Electricity from nuclear (TWh)']]
fil3_df

Исправленое задание

In [ ]:
df[df['Year'] > 2003]

In [19]:
df[df['Financial flows to developing countries (US $)'] > 10620000]

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
3,Afghanistan,2003.0,14.738506,9.5,8.09,25970000.0,36.66,0.31,0.0,0.63,...,229.96822,1.40,1220.000029,NaN,8.832278,190.683814,60.0,652230.0,33.939110,67.709953
7,Afghanistan,2007.0,36.051010,15.3,7.25,15750000.0,28.78,0.20,0.0,0.75,...,354.27990,1.53,1769.999981,NaN,13.826320,359.693158,60.0,652230.0,33.939110,67.709953
8,Afghanistan,2008.0,42.400000,16.7,7.49,16170000.0,21.17,0.19,0.0,0.54,...,607.83350,1.94,3559.999943,NaN,3.924984,364.663542,60.0,652230.0,33.939110,67.709953
10,Afghanistan,2010.0,42.700000,20.0,8.27,36500000.0,15.15,0.19,0.0,0.75,...,1182.89200,2.46,7110.000134,NaN,14.362441,543.306526,60.0,652230.0,33.939110,67.709953
11,Afghanistan,2011.0,43.222020,21.8,8.13,28690000.0,12.61,0.18,0.0,0.60,...,1436.11430,3.23,8930.000305,NaN,0.426355,591.190030,60.0,652230.0,33.939110,67.709953
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3624,Zambia,2017.0,40.300000,12.5,144.85,170340000.0,81.89,1.80,0.0,12.64,...,3202.07180,7.44,6809.999943,NaN,3.504336,1535.196574,25.0,752618.0,-13.133897,27.849332
3625,Zambia,2018.0,40.317890,11.9,140.76,54110000.0,82.28,2.24,0.0,13.89,...,3494.53690,7.35,7730.000019,NaN,4.034494,1516.368371,25.0,752618.0,-13.133897,27.849332
3626,Zambia,2019.0,43.000000,11.2,142.11,78570000.0,84.50,2.05,0.0,12.62,...,2983.88160,7.09,6800.000191,NaN,1.441306,1305.001031,25.0,752618.0,-13.133897,27.849332
3641,Zimbabwe,2013.0,40.498375,29.8,64.44,319000000.0,78.87,3.90,0.0,5.36,...,4085.33200,10.48,12279.999730,NaN,1.989493,1429.998461,38.0,390757.0,-19.015438,29.154857
3642,Zimbabwe,2014.0,32.300000,29.5,63.38,17830000.0,80.27,3.92,0.0,5.79,...,3940.88620,10.40,12079.999920,NaN,2.376929,1434.896277,38.0,390757.0,-19.015438,29.154857

In [21]:
df[df['Latitude'] > 0]

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
0,Afghanistan,2000.0,1.613591,6.20,9.22,20000.0,44.99,0.16,0.0,0.31,...,302.59482,1.64,760.000000,NaN,NaN,NaN,60.0,652230.0,33.939110,67.709953
1,Afghanistan,2001.0,4.074574,7.20,8.86,130000.0,45.60,0.09,0.0,0.50,...,236.89185,1.74,730.000000,NaN,NaN,NaN,60.0,652230.0,33.939110,67.709953
2,Afghanistan,2002.0,9.409158,8.20,8.47,3950000.0,37.83,0.13,0.0,0.56,...,210.86215,1.40,1029.999971,NaN,NaN,179.426579,60.0,652230.0,33.939110,67.709953
3,Afghanistan,2003.0,14.738506,9.50,8.09,25970000.0,36.66,0.31,0.0,0.63,...,229.96822,1.40,1220.000029,NaN,8.832278,190.683814,60.0,652230.0,33.939110,67.709953
4,Afghanistan,2004.0,20.064968,10.90,7.75,NaN,44.24,0.33,0.0,0.56,...,204.23125,1.20,1029.999971,NaN,1.414118,211.382074,60.0,652230.0,33.939110,67.709953
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3602,Yemen,2016.0,68.859505,61.20,2.94,NaN,2.48,4.36,0.0,0.16,...,1432.55220,NaN,NaN,NaN,NaN,NaN,56.0,527968.0,15.552727,48.516388
3603,Yemen,2017.0,79.200000,61.35,3.59,10000.0,2.80,3.63,0.0,0.19,...,1288.87670,NaN,NaN,NaN,NaN,NaN,56.0,527968.0,15.552727,48.516388
3604,Yemen,2018.0,62.000000,61.50,8.77,55730000.0,3.60,2.82,0.0,0.48,...,1170.72610,NaN,NaN,NaN,NaN,NaN,56.0,527968.0,15.552727,48.516388
3605,Yemen,2019.0,72.751076,61.30,8.57,1200000.0,3.11,2.93,0.0,0.48,...,1475.98520,NaN,NaN,NaN,NaN,NaN,56.0,527968.0,15.552727,48.516388
3606,Yemen,2020.0,73.757930,61.50,8.48,NaN,NaN,2.74,0.0,0.49,...,1092.00210,NaN,NaN,NaN,NaN,NaN,56.0,527968.0,15.552727,48.516388

##Группировка
Сгруппируйте датасет по какому-либо категориальному признаку и выведите среднее значение численных колонок (см. метод mean в pandas)

In [22]:
gr=df.groupby('Year').mean()
gr

<ipython-input-22-07660c2d883a>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  gr=df.groupby('Year').mean()

,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),Low-carbon electricity (% electricity),Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
Year,,,,,,,,,,,,,,,,,,,
2000.0,72.817088,57.616038,91.064444,2.661367e+07,35.152036,50.600359,13.845370,15.322275,37.696277,23091.306244,6.341720,128503.263497,10.853912,4.154007,7273.830530,141.850299,655936.275449,18.077710,13.196031
2001.0,73.317491,58.164780,85.957920,2.371608e+07,34.764157,51.942229,14.325031,14.977349,37.014818,23184.746223,6.236739,130756.332135,10.615472,3.469094,7163.821088,141.850299,655936.275449,18.077710,13.196031
2002.0,73.653604,58.713836,86.974080,2.461469e+07,34.681566,54.292470,14.379193,15.468976,37.389361,23602.782464,6.119225,132563.002288,10.471862,3.388653,7511.693640,141.850299,655936.275449,18.077710,13.196031
2003.0,74.221043,59.285535,87.396800,5.920176e+07,34.312048,57.299759,14.127081,15.630723,36.848809,24064.108713,6.120616,139107.728308,10.348676,3.951627,8751.626041,141.850299,655936.275449,18.077710,13.196031
2004.0,74.816961,59.821384,87.928480,2.573759e+07,34.138434,59.740663,14.792484,16.828976,37.018800,24680.670352,6.008856,145855.699774,10.666615,5.920613,10026.553019,141.850299,655936.275449,18.077710,13.196031
2005.0,75.215183,60.378302,88.811120,2.915921e+07,34.065482,62.533253,14.731366,17.633976,36.934670,25126.325023,5.835137,151461.359058,10.723585,5.256533,10952.271367,141.850299,655936.275449,18.077710,13.196031
2006.0,76.131521,60.937421,88.971440,3.029864e+07,33.767410,65.197289,14.880248,18.474699,36.321379,25027.290056,5.656855,156229.194483,10.850702,5.994346,12440.636926,141.850299,655936.275449,18.077710,13.196031
2007.0,76.590636,61.516770,102.643360,5.984462e+07,33.164226,69.143571,14.366810,18.919821,35.993770,25058.718975,5.477235,160713.183854,10.741687,5.741467,14013.706197,141.041420,648713.869822,18.376939,13.278801
2008.0,77.079213,62.063043,103.483440,3.335879e+07,33.267321,69.080595,14.226319,20.537619,36.619283,25155.733292,5.364147,161736.676690,11.129812,3.952797,15383.202223,141.041420,648713.869822,18.376939,13.278801
2009.0,77.399974,62.580435,108.559920,8.737154e+07,33.384643,68.365357,14.009387,20.991548,37.364870,24068.919953,5.331346,160096.148042,11.755286,-0.012907,13578.295201,141.041420,648713.869822,18.376939,13.278801
2010.0,78.169616,63.097205,110.818160,1.071827e+08,33.185179,73.479881,14.377362,22.843155,37.585780,24872.942504,5.288052,170203.204222,12.295647,4.199679,14182.204993,141.041420,648713.869822,18.376939,13.278801
2011.0,79.037925,63.609627,113.795440,9.100906e+07,32.867798,76.987024,13.640123,23.947738,37.120989,24437.764296,5.230694,175512.113720,12.003475,3.839754,15586.061955,141.041420,648713.869822,18.376939,13.278801
2012.0,79.895735,64.078571,117.425440,1.134200e+08,32.788155,78.973452,12.585890,25.765595,37.491657,24760.515758,5.004517,178096.736807,12.313950,4.138592,15547.837150,141.041420,648713.869822,18.376939,13.278801
2013.0,79.968893,64.140741,121.398175,1.236797e+08,33.007870,80.327751,12.675000,27.299645,38.309150,24483.219720,4.892840,181323.599201,13.133461,3.369241,15788.147451,140.317647,648688.076471,18.309293,13.384850
2014.0,80.712618,64.604630,126.089841,1.420680e+08,32.776509,81.870237,12.853659,29.003432,38.240419,24262.645804,4.805332,181583.394321,13.329087,3.291654,15871.146849,140.317647,648688.076471,18.309293,13.384850
2015.0,81.294154,65.017593,133.414524,1.224658e+08,32.514083,81.633195,12.942134,30.322071,37.871301,24340.982663,4.708967,180131.108216,13.625885,2.938853,14214.685163,140.317647,648688.076471,18.309293,13.384850
2016.0,82.413005,65.464506,141.332540,1.550925e+08,32.279290,82.833432,13.195732,32.191953,38.572396,24364.216159,4.710843,180106.208140,13.774507,3.045631,14337.754249,140.317647,648688.076471,18.309293,13.384850
2017.0,83.150414,65.858333,148.229286,1.911283e+08,32.141183,84.512426,13.447622,34.272012,38.861692,24534.107121,4.633735,186972.141515,13.936058,3.316764,15160.395096,140.317647,648688.076471,18.309293,13.384850
2018.0,83.916271,66.259877,153.733810,1.286281e+08,32.204320,87.179527,13.879024,36.674438,39.981266,24541.105738,4.605120,191085.387989,14.524124,3.298580,16100.672155,140.317647,648688.076471,18.309293,13.384850
2019.0,84.358197,66.653395,168.612460,9.626761e+07,32.016627,86.529586,14.336159,38.753550,40.069878,24228.296284,4.555783,191141.558685,14.812104,2.804089,15850.283459,140.317647,648688.076471,18.309293,13.384850
2020.0,85.054786,67.033025,174.124048,3.000000e+04,81.900000,84.098343,13.589024,41.234320,41.520707,22418.695139,10.000000,NaN,16.626240,-4.371673,14812.549396,140.317647,648688.076471,18.309293,13.384850

##Задание для гениев *
Агрегируйте числовой признак по категориальному признаку с использованием метода **без использования** библиотеки pandas, и вычислите медиану и среднее значение для каждой категории.

In [ ]:
#Агрегация